- Python 3: /private/var/mobile/Containers/Data/Application/77881549-3FA6-4E4B-803F-D53B172FC865/Documents/
  github: /private/var/mobile/Containers/Shared/AppGroup/144C0536-1309-4683-A623-34610B4D006A/File Provider Storage/github/
  hingebot: /private/var/mobile/Containers/Shared/AppGroup/144C0536-1309-4683-A623-34610B4D006A/File Provider Storage/hingebot/
  Textastic: /private/var/mobile/Containers/Data/Application/BE7DE533-3951-4E82-8625-B8A91389012F/Documents
  
- Three_simple_example:
    __any__: Python 3/www/webgl_loader_stl
    index.html: Python 3/www/webgl_loader_stl/simple_example.html
  Three_webgl_loader_stl:
    __any__: Python 3/www/webgl_loader_stl
    index.html: Python 3/www/webgl_loader_stl/webgl_loader_stl.html
  model_viewer_capstan:
    __any__: Python 3/www
    index.html: Python 3/www/model_viewer_capstan.html
  webgl_util_heads:
    __any__: Python 3/www
    index.html: Python 3/www/webgl-3d-camera-look-at-heads.html
  github:
    __any__: github/RichardPotthoff.github.io
    index.html: github/RichardPotthoff.github.io/index.md
    hingebot:
      __any__: hingebot
      index.html: hingebot/README.html
  textastic:
    __any__: Textastic
    index.html: Textastic/turtle.html
